name: Build

on:
  push:
    branches: [ "main"]
  pull_request:

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8', '3.9']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: npt
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: base-npt
          ref: ${{ github.base_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: npt-env
      - name: Activate conda environment, get python info, and install poppler
        run: |
          conda activate npt-env
          which python
          python --version
          conda install --file conda-requirements.txt
      - name: Install Poppler
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            conda install -c anaconda certifi openssl
            conda update openssl certifi
            conda install -c conda-forge/label/gcc7 poppler
            sudo apt-get update -y
            sudo apt-get install -y build-essential libpoppler-cpp-dev pkg-config python3-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install pkg-config poppler python
            conda install -c conda-forge poppler
          else
            conda install -c conda-forge poppler
            conda install -c conda-forge pdftotext
          fi
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .[dev,publishing]
      - name: Check style against standards using prospector
        run: prospector
      - name: Check import order
        run: isort --recursive --check-only auto_extract
      - name: Run unit tests
        run: pytest -v
      - name: Verify that we can build the package
        run: python setup.py sdist bdist_wheel
