name: Python package

on: [push, pull_request]

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.8', '3.9']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: npt
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: base-npt
          ref: ${{ github.base_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: npt-env
      - name: Activate conda environment and get python info
        run: |
          conda env list
          conda activate npt-env
          echo $CONDA_DEFAULT_ENV
          which python
          python --version
          which python3
          python3 --version
      - name: Install Poppler
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            conda update openssl ca-certificates certifi
            conda install -c conda-forge/label/gcc7 poppler
            sudo apt-get update -y
            sudo apt-get install build-essential libpoppler-cpp-dev pkg-config python-dev
          else
            conda install -c conda-forge poppler
          fi
      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install .[dev,publishing]
      - name: List packagae dir
        run: |
          conda list
          cd C:\Users\runneradmin\conda_pkgs_dir
          ls
      - name: Check style against standards using prospector
        run: prospector
      - name: Check import order
        run: isort --recursive --check-only auto_extract
      - name: Run unit tests
        run: pytest -v
      - name: Verify that we can build the package
        run: python3 setup.py sdist bdist_wheel
      #- name: Build documentation
      #  run: make coverage doctest html
      #  working-directory: docs
